config/routes.rb
Rails.application.routes.draw do
  
  ###### API ROUTES #######
  
  namespace :api, defaults: { format: :json } do
    scope module: :v1 do
      # We are going to list our resources here
      resources :users, :only => [:show]
      #FOR MESA
      resources :apitemplabels, :only => [:index, :create, :show]
      get 'csv', to: 'apitemplabels#spitcsv'
      #FOR Phoenix
      resources :apiphxtemplabels, :only => [:index, :create, :show]
      get 'phxcsv', to: 'apiphxtemplabels#spitcsv'
    end
  end
  
  #########################
  

  resources :productrequests

  resources :produce_order_items

  resources :produce_orders

  resources :rinventors

  resources :rev_inventories

  resources :allsales
  resources :orderitems
    resources :phxtemplabels 
  resources :templabels 
  get 'search_product_mesa', to: 'products#search_product_mesa'
  get 'search_product_phx', to: 'products#search_product_phx'
  get 'csv', to: 'templabels#spitcsv'
  get 'csvphx', to: 'phxtemplabels#spitcsv'
  get 'phxlabelmessage', to: 'phxtemplabels#labelmessage'
  get 'phxsendtoprintserver', to: 'phxtemplabels#phxsendtoprintserver'
  
  get 'labelmessage', to: 'templabels#labelmessage'
  #get 'totalsales', to: 'orderitems#totalsales'
  match 'totalsales', to: 'orderitems#totalsales', via: [:get, :post]
  match 'poorinventorydate', to: 'orderitems#poorinventorydate', via: [:get, :post]
  match 'poorinventory', to: 'orderitems#poorinventory', via: [:get, :post]
  match 'salesforproducedatebreakdown', to: 'orderitems#salesforproducedatebreakdown', via: [:get, :post]
  match 'salesforproducebreakdown', to: 'orderitems#salesforproducebreakdown', via: [:get, :post]
  
  match 'salesforproducedatephx', to: 'orderitems#salesforproducedatephx', via: [:get, :post]
  match 'salesforproducephx', to: 'orderitems#salesforproducephx', via: [:get, :post]
  
  match 'salesforproducedateall', to: 'orderitems#salesforproducedateall', via: [:get, :post]
  match 'salesforproduceall', to: 'orderitems#salesforproduceall', via: [:get, :post]
  
  match 'set_fullfilled', to: 'productrequests#set_fullfilled', via: [:get, :post]
  match 'set_notfullfilled', to: 'productrequests#set_notfullfilled', via: [:get, :post]

  match 'totalrevenuesalesdateall', to: 'orderitems#totalrevenuesalesdateall', via: [:get, :post]
  match 'totalrevenuesalesall', to: 'orderitems#totalrevenuesalesall', via: [:get, :post]

  match 'revenueforproducedateall', to: 'orderitems#revenueforproducedateall', via: [:get, :post]
  match 'revenueforproduceall', to: 'orderitems#revenueforproduceall', via: [:get, :post]
  
  match 'producemaintainance', to: 'products#produce', via: [:get, :post]
  match 'produceorderlocation', to: 'produce_orders#produceorderlocation', via: [:get, :post]
  
   match 'checkproduct', to: 'product_checks#checkproduct', via: [:get, :post]
  
  
  resources :products
  
  root to: 'templabels#index'


end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token
  
private
  
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

end

app/models/groupedincometotal.rb
class Groupedincometotal < ActiveRecord::Base

end

app/models/groupedtotal.rb
class Groupedtotal < ActiveRecord::Base

end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  
end

app/models/phxtemplabel.rb
class Phxtemplabel < ActiveRecord::Base
end

app/models/produce_order.rb
class ProduceOrder < ActiveRecord::Base
  has_many :produce_order_items
  
  def produce_order_items_attr=(produce_order_items_attr)
    produce_order_items_attr.each do |attributes|
        produce_order_items.build(attributes)
      end
  end

end

app/models/produce_order_item.rb
class ProduceOrderItem < ActiveRecord::Base
  belongs_to :produce_order
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/productrequest.rb
class Productrequest < ActiveRecord::Base
  
  validates :name, :email, :location, :presence => true

  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |poductrequest|
      csv << productrequest.attributes.values_at(*column_names)
    end
  end
end
  
end

app/models/rinventor.rb
class Rinventor < ActiveRecord::Base
end

app/models/templabel.rb
class Templabel < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/rinventors_controller.rb
class RinventorsController < ApplicationController
  before_action :set_rinventor, only: [:show, :edit, :update, :destroy]

  # GET /rinventors
  # GET /rinventors.json
  def index
    @rinventors = Rinventor.all
  end

  # GET /rinventors/1
  # GET /rinventors/1.json
  def show
  end

  # GET /rinventors/new
  def new
    @rinventor = Rinventor.new
  end

  # GET /rinventors/1/edit
  def edit
  end

  # POST /rinventors
  # POST /rinventors.json
  def create
    @rinventor = Rinventor.new(rinventor_params)

    respond_to do |format|
      if @rinventor.save
        format.html { redirect_to @rinventor, notice: 'Rinventor was successfully created.' }
        format.json { render :show, status: :created, location: @rinventor }
      else
        format.html { render :new }
        format.json { render json: @rinventor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rinventors/1
  # PATCH/PUT /rinventors/1.json
  def update
    respond_to do |format|
      if @rinventor.update(rinventor_params)
        format.html { redirect_to @rinventor, notice: 'Rinventor was successfully updated.' }
        format.json { render :show, status: :ok, location: @rinventor }
      else
        format.html { render :edit }
        format.json { render json: @rinventor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rinventors/1
  # DELETE /rinventors/1.json
  def destroy
    @rinventor.destroy
    respond_to do |format|
      format.html { redirect_to rinventors_url, notice: 'Rinventor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rinventor
      @rinventor = Rinventor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rinventor_params
      params.require(:rinventor).permit(:update_date, :rproductid, :starting_amount, :added_amount, :threshold, :sold_amount, :actual_amount, :theoretical_ending_inventory)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
  
   def flash_class(level)
        case level
          when 'notice' then "alert alert-info"
          when 'success' then "alert alert-success"
          when 'error' then "alert alert-danger"
          when 'alert' then "alert alert-warning"
        end
      end

end

app/helpers/csv_helper.rb
module CsvHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/phxtemplabels_helper.rb
module PhxtemplabelsHelper
end

app/helpers/produce_orders_helper.rb
module ProduceOrdersHelper
end

app/helpers/productrequests_helper.rb
module ProductrequestsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rinventors_helper.rb
module RinventorsHelper
end

app/helpers/templabels_helper.rb
module TemplabelsHelper
end

app/views/rinventors/_form.html.erb
<%= form_for(@rinventor) do |f| %>
  <% if @rinventor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rinventor.errors.count, "error") %> prohibited this rinventor from being saved:</h2>

      <ul>
      <% @rinventor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :update_date %><br>
    <%= f.date_select :update_date %>
  </div>
  <div class="field">
    <%= f.label :rproductid %><br>
    <%= f.number_field :rproductid %>
  </div>
  <div class="field">
    <%= f.label :starting_amount %><br>
    <%= f.text_field :starting_amount %>
  </div>
  <div class="field">
    <%= f.label :added_amount %><br>
    <%= f.text_field :added_amount %>
  </div>
  <div class="field">
    <%= f.label :threshold %><br>
    <%= f.text_field :threshold %>
  </div>
  <div class="field">
    <%= f.label :sold_amount %><br>
    <%= f.text_field :sold_amount %>
  </div>
  <div class="field">
    <%= f.label :actual_amount %><br>
    <%= f.text_field :actual_amount %>
  </div>
  <div class="field">
    <%= f.label :theoretical_ending_inventory %><br>
    <%= f.text_field :theoretical_ending_inventory %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rinventors/edit.html.erb
<h1>Editing rinventor</h1>

<%= render 'form' %>

<%= link_to 'Show', @rinventor %> |
<%= link_to 'Back', rinventors_path %>

app/views/rinventors/index.html.erb
<h1>Listing rinventors</h1>

<table>
  <thead>
    <tr>
      <th>Update date</th>
      <th>Rproductid</th>
      <th>Starting amount</th>
      <th>Added amount</th>
      <th>Threshold</th>
      <th>Sold amount</th>
      <th>Actual amount</th>
      <th>Theoretical ending inventory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rinventors.each do |rinventor| %>
      <tr>
        <td><%= rinventor.update_date %></td>
        <td><%= rinventor.rproductid %></td>
        <td><%= rinventor.starting_amount %></td>
        <td><%= rinventor.added_amount %></td>
        <td><%= rinventor.threshold %></td>
        <td><%= rinventor.sold_amount %></td>
        <td><%= rinventor.actual_amount %></td>
        <td><%= rinventor.theoretical_ending_inventory %></td>
        <td><%= link_to 'Show', rinventor %></td>
        <td><%= link_to 'Edit', edit_rinventor_path(rinventor) %></td>
        <td><%= link_to 'Destroy', rinventor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rinventor', new_rinventor_path %>

app/views/rinventors/new.html.erb
<h1>New rinventor</h1>

<%= render 'form' %>

<%= link_to 'Back', rinventors_path %>

app/views/rinventors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Update date:</strong>
  <%= @rinventor.update_date %>
</p>

<p>
  <strong>Rproductid:</strong>
  <%= @rinventor.rproductid %>
</p>

<p>
  <strong>Starting amount:</strong>
  <%= @rinventor.starting_amount %>
</p>

<p>
  <strong>Added amount:</strong>
  <%= @rinventor.added_amount %>
</p>

<p>
  <strong>Threshold:</strong>
  <%= @rinventor.threshold %>
</p>

<p>
  <strong>Sold amount:</strong>
  <%= @rinventor.sold_amount %>
</p>

<p>
  <strong>Actual amount:</strong>
  <%= @rinventor.actual_amount %>
</p>

<p>
  <strong>Theoretical ending inventory:</strong>
  <%= @rinventor.theoretical_ending_inventory %>
</p>

<%= link_to 'Edit', edit_rinventor_path(@rinventor) %> |
<%= link_to 'Back', rinventors_path %>