config/routes.rb
Rails.application.routes.draw do
  
  ###### API ROUTES #######
  
  namespace :api, defaults: { format: :json } do
    scope module: :v1 do
      # We are going to list our resources here
      resources :users, :only => [:show]
      #FOR MESA
      resources :apitemplabels, :only => [:index, :create, :show]
      get 'csv', to: 'apitemplabels#spitcsv'
      #FOR Phoenix
      resources :apiphxtemplabels, :only => [:index, :create, :show]
      get 'phxcsv', to: 'apiphxtemplabels#spitcsv'
    end
  end
  
  #########################
  

  resources :productrequests

  resources :produce_order_items

  resources :produce_orders

  resources :rinventors

  resources :rev_inventories

  resources :allsales
  resources :orderitems
    resources :phxtemplabels 
  resources :templabels 
  get 'search_product_mesa', to: 'products#search_product_mesa'
  get 'search_product_phx', to: 'products#search_product_phx'
  get 'csv', to: 'templabels#spitcsv'
  get 'csvphx', to: 'phxtemplabels#spitcsv'
  get 'phxlabelmessage', to: 'phxtemplabels#labelmessage'
  get 'phxsendtoprintserver', to: 'phxtemplabels#phxsendtoprintserver'
  
  get 'labelmessage', to: 'templabels#labelmessage'
  #get 'totalsales', to: 'orderitems#totalsales'
  match 'totalsales', to: 'orderitems#totalsales', via: [:get, :post]
  match 'poorinventorydate', to: 'orderitems#poorinventorydate', via: [:get, :post]
  match 'poorinventory', to: 'orderitems#poorinventory', via: [:get, :post]
  match 'salesforproducedatebreakdown', to: 'orderitems#salesforproducedatebreakdown', via: [:get, :post]
  match 'salesforproducebreakdown', to: 'orderitems#salesforproducebreakdown', via: [:get, :post]
  
  match 'salesforproducedatephx', to: 'orderitems#salesforproducedatephx', via: [:get, :post]
  match 'salesforproducephx', to: 'orderitems#salesforproducephx', via: [:get, :post]
  
  match 'salesforproducedateall', to: 'orderitems#salesforproducedateall', via: [:get, :post]
  match 'salesforproduceall', to: 'orderitems#salesforproduceall', via: [:get, :post]
  
  match 'set_fullfilled', to: 'productrequests#set_fullfilled', via: [:get, :post]
  match 'set_notfullfilled', to: 'productrequests#set_notfullfilled', via: [:get, :post]

  match 'totalrevenuesalesdateall', to: 'orderitems#totalrevenuesalesdateall', via: [:get, :post]
  match 'totalrevenuesalesall', to: 'orderitems#totalrevenuesalesall', via: [:get, :post]

  match 'revenueforproducedateall', to: 'orderitems#revenueforproducedateall', via: [:get, :post]
  match 'revenueforproduceall', to: 'orderitems#revenueforproduceall', via: [:get, :post]
  
  match 'producemaintainance', to: 'products#produce', via: [:get, :post]
  match 'produceorderlocation', to: 'produce_orders#produceorderlocation', via: [:get, :post]
  
   match 'checkproduct', to: 'product_checks#checkproduct', via: [:get, :post]
  
  
  resources :products
  
  root to: 'templabels#index'


end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  before_create :generate_access_token
  
private
  
  def generate_access_token
    begin
      self.access_token = SecureRandom.hex
    end while self.class.exists?(access_token: access_token)
  end

end

app/models/groupedincometotal.rb
class Groupedincometotal < ActiveRecord::Base

end

app/models/groupedtotal.rb
class Groupedtotal < ActiveRecord::Base

end

app/models/orderitem.rb
class Orderitem < ActiveRecord::Base
  
end

app/models/phxtemplabel.rb
class Phxtemplabel < ActiveRecord::Base
end

app/models/produce_order.rb
class ProduceOrder < ActiveRecord::Base
  has_many :produce_order_items
  
  def produce_order_items_attr=(produce_order_items_attr)
    produce_order_items_attr.each do |attributes|
        produce_order_items.build(attributes)
      end
  end

end

app/models/produce_order_item.rb
class ProduceOrderItem < ActiveRecord::Base
  belongs_to :produce_order
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/productrequest.rb
class Productrequest < ActiveRecord::Base
  
  validates :name, :email, :location, :presence => true

  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |poductrequest|
      csv << productrequest.attributes.values_at(*column_names)
    end
  end
end
  
end

app/models/rinventor.rb
class Rinventor < ActiveRecord::Base
end

app/models/templabel.rb
class Templabel < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/produce_orders_controller.rb
class ProduceOrdersController < ApplicationController
  before_action :set_produce_order, only: [:show, :edit, :update, :destroy]

  # GET /produce_orders
  # GET /produce_orders.json
  def index
    @produce_orders = ProduceOrder.all
  end

  # GET /produce_orders/1
  # GET /produce_orders/1.json
  def show
  end
  
  def produceorderlocation
    if params[:location]
    location = params[:location]
    redirect_to :action => 'new', :location => location
    end
  end

  # GET /produce_orders/new
  def new
    
    if ( params[:location] == "/products/ProductCategory/120/")
      @store = "Mesa"
    else
      @store = "Phoenix"
    end
    
    @produce_order = ProduceOrder.new
    @producenum = Product.where(category: params[:location]).count
    @allproduce = Product.where(category: params[:location])
    
    
    @producenum.times {@produce_order.produce_order_items.build}
  end

  # GET /produce_orders/1/edit
  def edit
  end

  # POST /produce_orders
  # POST /produce_orders.json
  def create
    @produce_order = ProduceOrder.new(produce_order_params)
    respond_to do |format|
      if @produce_order.save
        #ProduceOrderMailer.send_simple_message(@produce_order).deliver
        ProduceOrderMailer.produce_order_email(@produce_order).deliver
        format.html { redirect_to @produce_order, notice: 'Produce order was successfully created.' }
        format.json { render :show, status: :created, location: @produce_order }
      else
        format.html { render :new }
        format.json { render json: @produce_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produce_orders/1
  # PATCH/PUT /produce_orders/1.json
  def update
    respond_to do |format|
      if @produce_order.update(produce_order_params)
        format.html { redirect_to @produce_order, notice: 'Produce order was successfully updated.' }
        format.json { render :show, status: :ok, location: @produce_order }
      else
        format.html { render :edit }
        format.json { render json: @produce_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produce_orders/1
  # DELETE /produce_orders/1.json
  def destroy
    @produce_order.destroy
    respond_to do |format|
      format.html { redirect_to produce_orders_url, notice: 'Produce order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produce_order
      @produce_order = ProduceOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produce_order_params
     params.require(:produce_order).permit(:vendor, :orderdate, produce_order_items_attr: [:id, :producename, :quantity, :instock, :remark])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, :sort => column, :direction => direction
  end
  
   def flash_class(level)
        case level
          when 'notice' then "alert alert-info"
          when 'success' then "alert alert-success"
          when 'error' then "alert alert-danger"
          when 'alert' then "alert alert-warning"
        end
      end

end

app/helpers/csv_helper.rb
module CsvHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/phxtemplabels_helper.rb
module PhxtemplabelsHelper
end

app/helpers/produce_orders_helper.rb
module ProduceOrdersHelper
end

app/helpers/productrequests_helper.rb
module ProductrequestsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/rinventors_helper.rb
module RinventorsHelper
end

app/helpers/templabels_helper.rb
module TemplabelsHelper
end

app/views/produce_orders/_form.html.erb
<%= form_for(@produce_order) do |f| %>
  <% if @produce_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produce_order.errors.count, "error") %> prohibited this produce_order from being saved:</h2>

      <ul>
      <% @produce_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="field">
   
    <%= f.label :vendor %><br>
    <%= f.text_field :vendor %>
  </div>
  <div class="field">
    <%= f.label :orderdate %><br>
    <%= f.date_select :orderdate %>
  </div>

  <div>
  <table class="table table-bordered table-striped">
    <thead>
          <tr>
              <th>Produce</th>
              <th>Order Qty</th>
              <th>Instock Qty</th>
              <th>Remark</th>
              <th>Weekly Avg.</th>
          </tr>
      </thead>

  <tbody>
    <% @produce_order.produce_order_items.each.with_index do |produce_order_item,index| %>

      <%= fields_for "produce_order[produce_order_items_attr][]", produce_order_item do |task_form| %>
        <tr>
           <td><%= @allproduce.fetch(index).name.to_s %> <%= task_form.hidden_field :producename, :value => @allproduce.fetch(index).name.to_s %> </td>
           <td> <%= task_form.text_field :quantity %> </td>
          <td> <%= task_form.text_field :instock %> </td>
          <td> <%= task_form.text_field :remark %> </td>
          <% @date1 = 9.days.ago 
             @date2 = @date1 + 7.days 
             @psale = Groupedtotal
                .select("name, SUM(totalsold) as totalsold, productid")
                .where(created_date: @date1..@date2)
                .where(productid: @allproduce.fetch(index).revid)
                .group("name, productid") %>
          
          <td> 
            <% begin %>
            <%= @psale.first.totalsold.round(2) %> 
            <% rescue 
                next
               end %> </td>
        </tr>
      <% end %>
      <% end %>
  </tbody>
  </table>
  </div>

  <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
<i class="icon-ok icon-white"></i> Create Order
<% end %> 
<br><br>
<% end %>

app/views/produce_orders/edit.html.erb
<h1>Editing produce_order</h1>

<%= render 'form' %>

<%= link_to 'Show', @produce_order %> |
<%= link_to 'Back', produce_orders_path %>

app/views/produce_orders/index.html.erb
<h1>Listing All Produce Order</h1>

  <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Vendor</th>
      <th>Orderdate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produce_orders.each do |produce_order| %>
      <tr>
        <td><%= produce_order.vendor %></td>
        <td><%= produce_order.orderdate %></td>
        <td><%= link_to 'Show', produce_order %></td>
        <td><%= link_to 'Edit', edit_produce_order_path(produce_order) %></td>
        <td><%= link_to 'Destroy', produce_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Produce order', new_produce_order_path %>

app/views/produce_orders/new.html.erb
<h1>New Produce Order for <%= @store %></h1>

<%= render 'form' %>

<%= link_to 'Back', produce_orders_path %>

app/views/produce_orders/produceorderlocation.html.erb
<h2> Please select store location to order Produce </h2>
<%= form_tag(produceorderlocation_path) do %>
<%= select_tag("location", options_for_select([['Mesa', '/products/ProductCategory/120/'],
  ['Phoenix', '/products/ProductCategory/539/']])) %>

<%= submit_tag "Submit", :disable_with => "Submitting..." %>
<% end %>

app/views/produce_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendor:</strong>
  <%= @produce_order.vendor %>
</p>

<p>
  <strong>Orderdate:</strong>
  <%= @produce_order.orderdate %>
</p>

 <h2>Order Items</h2>
<div>
<table class="table table-bordered table-striped">
  <thead>
        <tr>
            <th>Produce</th>
            <th>Order Qty</th>
            <th>InStock Qty</th>
            <th>Remark</th>
        </tr>
    </thead>

<tbody>
 
    <% @produce_order.produce_order_items.each do |item| %>
   <tr>
     <td> <%= item.producename %> </td>
      <td>  <%= item.quantity %> </td>
     <td> <%= item.instock %> </td>
     <td>  <%= item.remark %> </td>
   </tr>
    <% end %>
  
</tbody>
</table>
</div>

<%= link_to 'Edit', edit_produce_order_path(@produce_order) %> 