config/routes.rb
Rails.application.routes.draw do
  
  ###### API ROUTES #######
  
  namespace :api, defaults: { format: :json } do
    scope module: :v1 do
      # We are going to list our resources here
      resources :users, :only => [:show]
      #FOR MESA
      resources :apitemplabels, :only => [:index, :create, :show]
      get 'csv', to: 'apitemplabels#spitcsv'
      #FOR Phoenix
      resources :apiphxtemplabels, :only => [:index, :create, :show]
      get 'phxcsv', to: 'apiphxtemplabels#spitcsv'
    end
  end
  
  #########################
  

  resources :productrequests

  resources :produce_order_items

  resources :produce_orders

  resources :rinventors

  resources :rev_inventories

  resources :allsales
  resources :orderitems
    resources :phxtemplabels 
  resources :templabels 
  get 'search_product_mesa', to: 'products#search_product_mesa'
  get 'search_product_phx', to: 'products#search_product_phx'
  get 'csv', to: 'templabels#spitcsv'
  get 'csvphx', to: 'phxtemplabels#spitcsv'
  get 'phxlabelmessage', to: 'phxtemplabels#labelmessage'
  get 'phxsendtoprintserver', to: 'phxtemplabels#phxsendtoprintserver'
  
  get 'labelmessage', to: 'templabels#labelmessage'
  #get 'totalsales', to: 'orderitems#totalsales'
  match 'totalsales', to: 'orderitems#totalsales', via: [:get, :post]
  match 'poorinventorydate', to: 'orderitems#poorinventorydate', via: [:get, :post]
  match 'poorinventory', to: 'orderitems#poorinventory', via: [:get, :post]
  match 'salesforproducedatebreakdown', to: 'orderitems#salesforproducedatebreakdown', via: [:get, :post]
  match 'salesforproducebreakdown', to: 'orderitems#salesforproducebreakdown', via: [:get, :post]
  
  match 'salesforproducedatephx', to: 'orderitems#salesforproducedatephx', via: [:get, :post]
  match 'salesforproducephx', to: 'orderitems#salesforproducephx', via: [:get, :post]
  
  match 'salesforproducedateall', to: 'orderitems#salesforproducedateall', via: [:get, :post]
  match 'salesforproduceall', to: 'orderitems#salesforproduceall', via: [:get, :post]
  
  match 'set_fullfilled', to: 'productrequests#set_fullfilled', via: [:get, :post]
  match 'set_notfullfilled', to: 'productrequests#set_notfullfilled', via: [:get, :post]

  match 'totalrevenuesalesdateall', to: 'orderitems#totalrevenuesalesdateall', via: [:get, :post]
  match 'totalrevenuesalesall', to: 'orderitems#totalrevenuesalesall', via: [:get, :post]

  match 'revenueforproducedateall', to: 'orderitems#revenueforproducedateall', via: [:get, :post]
  match 'revenueforproduceall', to: 'orderitems#revenueforproduceall', via: [:get, :post]
  
  match 'producemaintainance', to: 'products#produce', via: [:get, :post]
  match 'produceorderlocation', to: 'produce_orders#produceorderlocation', via: [:get, :post]
  
   match 'checkproduct', to: 'product_checks#checkproduct', via: [:get, :post]
  
  
  resources :products
  
  root to: 'templabels#index'


end

app/models/productrequest.rb
class Productrequest < ActiveRecord::Base
  
  validates :name, :email, :location, :presence => true

  def self.to_csv(options = {})
  CSV.generate(options) do |csv|
    csv << column_names
    all.each do |poductrequest|
      csv << productrequest.attributes.values_at(*column_names)
    end
  end
end
  
end

app/controllers/productrequests_controller.rb
class ProductrequestsController < ApplicationController
  layout 'productrequest'
  http_basic_authenticate_with name: "admin", password: "1af2af3af4af5", except: [:new, :create]
  before_action :set_productrequest, only: [:show, :edit, :update, :destroy]
  helper_method :set_fullfilled

  # GET /productrequests
  # GET /productrequests.json
  def index
    @productrequests = Productrequest.where("status = ?", "active")
    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"product-requests.csv\""
        headers['Content-Type'] ||= 'text/csv'
    end
  end
  end

  # GET /productrequests/1
  # GET /productrequests/1.json
  def show
  end

  # GET /productrequests/new
  def new
    @productrequest = Productrequest.new
  end

  # GET /productrequests/1/edit
  def edit
  end

  # POST /productrequests
  # POST /productrequests.json
  def create
    @productrequest = Productrequest.new(productrequest_params)
    @productrequest.status = "active"
    respond_to do |format|
      if @productrequest.save
        format.html { 
          flash[:success] = "Your product request has been created"       
              #SENDING EMAIL TO ADMIN THAT REQUEST HAS BEEN SUBMITED          
              ProductrequestMailer.productrequest_email(@productrequest).deliver
              #SENDING EMAIL TO CUSTOMER THAT WE HAVE RECEIVED YOUR EMAIL
              ProductrequestMailer.productrequest_inprogress_email(@productrequest).deliver
          begin
              #BELOW IS CODE FOR SUBSCRIBING USER TO OUR MAILCHIMP LIST USING GIBBON
              gb = Gibbon::API.new("93f3019f32a6215c04959711c63d894e-us3")
              gb.lists.subscribe({:id => '8bacae7aa7', :email => {:email => @productrequest.email}, :merge_vars => {:FNAME => 'First Name', :LNAME => 'Last Name'}, :double_optin => false})
          rescue Gibbon::MailChimpError => e
            # do something with e.message here
          end
          
          redirect_to new_productrequest_path }
        format.json { render :show, status: :created, location: @productrequest }
      else
        format.html { render :new }
        format.json { render json: @productrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productrequests/1
  # PATCH/PUT /productrequests/1.json
  def update
    respond_to do |format|
      if @productrequest.update(productrequest_params)
        format.html { redirect_to @productrequest, notice: 'Productrequest was successfully updated.' }
        format.json { render :show, status: :ok, location: @productrequest }
      else
        format.html { render :edit }
        format.json { render json: @productrequest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productrequests/1
  # DELETE /productrequests/1.json
  def destroy
    @productrequest.destroy
    respond_to do |format|
      format.html { redirect_to productrequests_url, notice: 'Productrequest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def set_fullfilled
      @productrequest = Productrequest.find(params[:pid])
      @productrequest.status = "fullfilled"
      if @productrequest.save
        ProductrequestMailer.productrequest_fullfilled_email(@productrequest).deliver
        redirect_to productrequests_url, notice: 'Product Request was Fullfilled.' 
      end
  end
  
  def set_notfullfilled
      @productrequest = Productrequest.find(params[:pid])
      @productrequest.status = "notfullfilled"
      if @productrequest.save
        ProductrequestMailer.productrequest_notfullfilled_email(@productrequest).deliver
        redirect_to productrequests_url, notice: 'Product Request was set to NotFullfilled.' 
      end
  end  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_productrequest
      @productrequest = Productrequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def productrequest_params
      params.require(:productrequest).permit(:name, :email, :phone, :fullfilled, :location)
    end
end

app/helpers/productrequests_helper.rb
module ProductrequestsHelper
end

app/views/productrequests/_form.html.erb
<%= bootstrap_form_for(@productrequest) do |f| %>
  <% if @productrequest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@productrequest.errors.count, "error") %> prohibited this productrequest from being saved:</h2>

      <ul>
      <% @productrequest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.text_field :name, label: "Product Name" %>
  </div>
  <div class="field">
    <%= f.text_field :email, label: "Email (Required)" %>
  </div>
  <div class="field">
    <%= f.text_field :phone, label: "Phone (Optional)" %>
  </div>

  <div class="field">
    <%= f.select :location, [['North Phoenix','phx'],['Mesa','mesa']], include_blank: "Please Select"  %>

  </div>
  <div class="actions">
    <%= f.submit "Submit Request", data: { disable_with: "Please wait..." } %> 
  </div>

<h3> We will try our best to get your requested product to our store as soon as possible. We will notify you via email unless you entered your phone number. Thank You</h3>
<% end %>

app/views/productrequests/edit.html.erb
<h1>Editing productrequest</h1>

<%= render 'form' %>

<%= link_to 'Show', @productrequest %> |
<%= link_to 'Back', productrequests_path %>

app/views/productrequests/index.csv.erb
<%- headers = ['ProductName', 'Email', 'Date', 'Location', 'Status'] -%>
<%= CSV.generate_line headers %>
<%- @productrequests.each do |pr| -%>
    <%= CSV.generate_line([pr.name, pr.email, pr.created_at, pr.location, pr.status]).html_safe.strip %>
<%- end -%>

app/views/productrequests/index.html.erb
  <img src="<%= asset_path( 'logo.jpg' ) %>" />

<h1>Listing Requests</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created On</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Location</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productrequests.each do |productrequest| %>
      <tr>
        <td><%= productrequest.name %></td>
        <td><%= productrequest.created_at.strftime('%B %e %Y') %></td>
        <td><%= productrequest.email %></td>
        <td><%= productrequest.phone %></td>
        <td><%= productrequest.location %></td>
        <td><%= productrequest.status %></td>
        <td><%= link_to 'Fullfilled', set_fullfilled_path(pid: productrequest.id) %></td>
        <td><%= link_to 'NotFullfilled', set_notfullfilled_path(pid: productrequest.id) %></td>
        <td><%= link_to 'Destroy', productrequest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Download:
<%= link_to "Download CSV", productrequests_path(format: "csv") %>

<br>

app/views/productrequests/new.html.erb
  <% flash.each do |key, value| %>
        <div class="<%= flash_class(key) %>">
              <%= value %>
        </div>
  <% end %>
<script>
    setTimeout("$('.alert-success').fadeOut('slow')", 3000)
</script>

  <img src="<%= asset_path( 'logo.jpg' ) %>" />


<h1>Enter a Product Request</h1>

<%= render 'form' %>

app/views/productrequests/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @productrequest.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @productrequest.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @productrequest.phone %>
</p>

<p>
  <strong>Fullfilled:</strong>
  <%= @productrequest.fullfilled %>
</p>

<p>
  <strong>Location:</strong>
  <%= @productrequest.location %>
</p>

<%= link_to 'Edit', edit_productrequest_path(@productrequest) %> |
<%= link_to 'Back', productrequests_path %>